from typing import TypedDict, Annotated, List, Optional, Literal
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages


class Attempt(TypedDict):
    """Represents a single SQL generation attempt."""
    sql: str
    error: str


class AgentState(TypedDict):
    """
    The central state object for the Data Analysis Agent.
    
    Attributes:
        session_id: The unique session identifier
        query: The original user query
        reformed_query: The query after context resolution (from router)
        messages: Full conversation history with LangChain message format
        intent: Classified intent ('sql_agent' or 'qa_bot')
        title: Session title (generated on first message)
        response: The final response to return to user
        
        # SQL-specific state
        attempt_history: List of failed SQL attempts for retry logic
        n_iterations: Current iteration count for SQL generation
        sql_result: The result from BigQuery execution
        generated_sql: The SQL query generated by the model
        
        # Configuration
        model_name: The model to use (for configurable routing)
        temperature: Temperature setting for response generation
        reasoning_budget: Reasoning budget level
    """
    # Core session info
    session_id: str
    query: str
    reformed_query: Optional[str]
    
    # Message history (uses add_messages reducer for proper merging)
    messages: Annotated[List[AnyMessage], add_messages]
    
    # Routing info
    intent: Optional[Literal["sql_agent", "qa_bot"]]
    title: Optional[str]
    
    # Response
    response: Optional[str]
    
    # SQL generation state
    attempt_history: List[Attempt]
    n_iterations: int
    sql_result: Optional[str]
    generated_sql: Optional[str]
    
    # Runtime configuration
    model_name: Optional[str]
    temperature: Optional[float]
    reasoning_budget: Optional[str]
