from typing import TypedDict, Annotated, List, Optional
from langchain_core.messages import BaseMessage
import operator

class AgentState(TypedDict):
    """
    The central state object for the Data Analysis Agent.
    """
    # The conversation history, allowing the agent to remember previous turns.
    # The 'operator.add' reducer ensures new messages are appended, not overwritten.
    messages: Annotated[List[BaseMessage], operator.add]
    
    # The structured intent derived from the user's query (e.g., "Cohort Analysis", "Simple Retrieval").
    query_intent: str
    
    # The most recent SQL query generated by the agent.
    current_sql: Optional[str]
    
    # The raw results returned from the BigQuery executor.
    query_results: Optional[List[dict]]
    
    # Capture of any exceptions raised during execution (e.g., "Column not found").
    error_trace: Optional[str]
    
    # A counter to track the number of self-correction attempts to prevent infinite loops.
    iteration_count: int